### ISSUE TITLE
Files have executable permission

### ISSUE THREAD

**Issue by stuaxo** [rjopek/glfw-cairo#1]
Hi,
  Thanks for making glfw-cairo.

For some reason the files here all have executable permission + probably shouldn't.

S

**Comment by stuaxo** [comment]
PR  https://github.com/rjopek/glfw-cairo/pull/2

**Comment by rjopek** [comment]
Hi,

These are my humble beginnings of writing GLFW Cairo,
in the beginning there was a test and it stayed that way.
cairo-xlib is the most interesting gl_00.c

As for your question, I don't quite understand.

-- Rafał

**Comment by rjopek** [comment]
When applying permissions to directories on Linux, the permission bits have different meanings than on regular files.

**Comment by stuaxo** [comment]
Yep, it's easily done to accidentally add +x to everything, it's only the directories themselves that need the executable bit set.

To fix the files, I unset only the files:

`$ find . -type f -exec chmod -x {} \;`

If you ever need to set only the directories as executable, you can do the opposite, but using `-d` for directory:

`$ find . -type d -exec chmod u+x {} \;

Thanks for merging this.
