### ISSUE TITLE
examples/cairo-gl/gl_00.c flickers.

### ISSUE THREAD

**Issue by stuaxo** [rjopek/glfw-cairo#4]
On Ubuntu 22.04, 64 bit x86 on AMD Ryzen with Mesa on Oibaf PPA and AMD kernel.

When I run this example the screen is black.

If I move the mouse the image flickers, repeatedly showing the rounding rectangle and then drawing black over it straight away -

(warning video contains flashing!)
[2022-09-21 21-33-36.webm](https://user-images.githubusercontent.com/179677/191606999-c216f5fb-1160-419f-a058-d704901bb58c.webm)

If I enlarge the window, the black area stays over the area of the initial window size, while the flickering shape covers the full size window:

![Screenshot from 2022-09-21 21-03-16](https://user-images.githubusercontent.com/179677/191600049-ed4eddc9-9bcd-48ea-9a2b-00d80c5a269d.png)

**Comment by rjopek** [comment]
Hi Stuart,

Thanks for checking and making this example, on my old hardware the example worked fine
for this reason I decided to add this example, other than that, I really don't know what to tell you.

Thank you again,
-- Rafał

**Comment by stuaxo** [comment]
That's fine, I'd like the example to stay in, so let's keep this bug open, either we will be able to fix it or someone else may arrive with some insight.

Can you run

`$ glxinfo | grep OpenGL`

And paste the output, so I can get some info on the graphics hardware?  - there can be some subtle differences in the way they handle things.


I've also got access to an old mac mini which has intel graphics (though I need to dig it out), as well as some raspberry pis I can try this with.

**Comment by rjopek** [comment]
All tests are done on Samsung Touch,

```
OpenGL vendor string: Mesa/X.org
OpenGL renderer string: llvmpipe (LLVM 14.0.5, 256 bits)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 22.2.0-devel (git-e8fc5cc 2022-06-22 focal-oibaf-ppa)
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.5 (Compatibility Profile) Mesa 22.2.0-devel (git-e8fc5cc 2022-06-22 focal-oibaf-ppa)
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 22.2.0-devel (git-e8fc5cc 2022-06-22 focal-oibaf-ppa)
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

**Comment by stuaxo** [comment]
Ah, interesting setup, I might be able to try an LLVMPipe setup somewhere.

I'll have to see if this works on a raspberry pi + can reproduce the bug there.

It's a long time since I did much with opengl, I think I need to understand swapbuffers a bit more to work out what's up.

I wonder if this should have a callback for window resizing for that to work better here ?
https://stackoverflow.com/questions/45880238/how-to-draw-while-resizing-glfw-window#56614042

**Comment by stuaxo** [comment]
Extra info:  I ran the sdl example, and it doesn't have the same issue (possibly this is expected).
